<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Abp" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SixThreeTwo_shop.Core\SixThreeTwo_shop.Core.csproj" />
    </ItemGroup>

</Project>
